Repository gematik/api-erp, pull requests merged in 2023-05, with the labels that each got.

#54 Links für TA7 Anlage 2 repariert
  docs/erp_fhirversion.adoc
  docs_sources/erp_fhirversion-source.adoc
Labels: bug

#62 Update der Pakete für das Korrekturrelease der KBV
  docs/erp_fhirversion.adoc
  docs/erp_versionsuebergang.adoc
  docs_sources/erp_fhirversion-source.adoc
  docs_sources/erp_versionsuebergang-source.adoc
  images/puml_fhir_version_timeline.png
  puml/fhir_version_timeline.puml
Labels: enhancement

#32 Aufnahme HTTP-Fehlercode 512 für fehlgeschlagene OCSP Prüfungen im Backend
  docs/erp_bereitstellen.adoc
  docs/erp_chargeItem.adoc
  docs/erp_statuscodes.adoc
  docs/erp_steuerung_durch_le.adoc
  docs_sources/erp_bereitstellen-source.adoc
  docs_sources/erp_chargeItem-source.adoc
  docs_sources/erp_statuscodes-source.adoc
  docs_sources/erp_steuerung_durch_le-source.adoc
  resources/scripts/build_with_replace_includes.sh
Labels: documentation, enhancement
