Repository gematik/api-erp, pull requests merged in 2024-02, with the labels that each got.

#107 Hinweis zur Vermeidung von non-printables in Nachrichten des Versicherten
  docs/erp_communication.adoc
  docs_sources/erp_communication-source.adoc
Labels: enhancement

#113 Neue Quittung als Beispiel
  docs/erp_abrufen.adoc
  docs_sources/erp_abrufen-source.adoc
  resources/examples/ti-dienste/task/response_taskClose.xml
Labels: enhancement

#111 korrigiere das Dokument bezüglich der JWT-Signatur.
  docs/erp_versicherte.adoc
  docs_sources/erp_versicherte-source.adoc
  resources/examples/ti-dienste/task/versicherte/response_taskGetSingle.json
Labels: enhancement, waiting

#123 Hinweis für Datenlimit eingefügt
  docs/erp_abrufen.adoc
  docs_sources/erp_abrufen-source.adoc
Labels: enhancement

#122 Zusätzliche Dokumentation für das E-Rezept-FdV
  README.md
  docs/certificate_check.adoc
  docs/erp_chargeItem.adoc
  docs/erp_communication.adoc
  docs/erp_versicherte.adoc
  docs/misc_api_endpoints.adoc
  docs_sources/certificate_check-source.adoc
  docs_sources/erp_chargeItem-source.adoc
  docs_sources/erp_communication-source.adoc
  docs_sources/erp_versicherte-source.adoc
  docs_sources/misc_api_endpoints-source.adoc
  resources/examples/ti-dienste/cert/response_certList.json
  resources/examples/ti-dienste/cert/response_ocspList.json
  resources/examples/ti-dienste/erp/CapabilityStatement_RU.xml
  resources/examples/ti-dienste/medicationdispense/response_get-multiple-medication-dispense.json
  resources/examples/ti-dienste/medicationdispense/response_get-single-medicationdispense-by-id.json
Labels: enhancement

#126 Beschreibung für Recovery Secret hinzufügen
  docs/erp_abrufen.adoc
  docs_sources/erp_abrufen-source.adoc
  resources/examples/ti-dienste/task/request_recovery_secret.xml
  resources/examples/ti-dienste/task/response_taskAccept.xml
Labels: documentation, enhancement

#127 Beschreibung von kvnr-Parameter für PN3
  docs/erp_abrufen_egk.adoc
  docs_sources/erp_abrufen_egk-source.adoc
Labels: enhancement
